ci: update pipeline

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,20 +1,53 @@
 version: 2.1
+orbs:
+  node: circleci/node@4.2.0
+  go: circleci/go@1.6.0
+
+commands:
+  set-version:
+    steps:
+      - run:
+          name: read version file and export to APP_VERISON
+          command: |
+            export APP_VERSION=$(cat .version)
+            echo "export APP_VERSION=${APP_VERSION}" >> $BASH_ENV
+            echo "read in version ${APP_VERSION}"
 
 jobs:
-  build:
+  get-version:
+    executor: node/default
+    steps:
+      - checkout
+      - node/install-packages
+      - run:
+          name: export version variable
+          command: |
+            export APP_VERSION="$(npx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/')"
+            export NPX_STATUS="${PIPESTATUS[0]} ${PIPESTATUS[1]}"
+            if [ ${NPX_STATUS} -ne 0 ]; then
+              echo "failed to run semantic release"
+              exit ${NPX_STATUS}
+            fi
+            if [ -z "${APP_VERSION}" ]; then
+              echo "no new version detected"
+            else
+              echo "found next Version ${APP_VERSION}"
+            fi
+            echo "${APP_VERSION}" > .version
+      - persist_to_workspace:
+          root: .
+          paths:
+            - .version
+  test:
     docker:
-      - image: circleci/golang:1.12
-        environment:
-          - GO111MODULE: "on"
+      - image: 'cimg/go:1.14'
     working_directory: /go/src/github.com/signavio/aws-mfa-login
     steps:
-      - run: git config --global url.ssh://git@github.com/signavio.insteadOf https://github.com/signavio
       - checkout
-      - run:
-          name: install-tools
-          command: |
-            go get -u github.com/mitchellh/gox
-            go get -u github.com/stevenmatthewt/semantics
+      - set-version
+      - go/load-cache
+      - go/mod-download
+      - go/save-cache
       - run:
           name: test
           command: |
@@ -23,58 +56,66 @@ jobs:
           name: upload code coverage
           command: |
             bash <(curl -s https://codecov.io/bash)
+
+  build:
+    docker:
+      - image: 'cimg/go:1.14'
+    working_directory: /go/src/github.com/signavio/aws-mfa-login
+    steps:
+      - checkout
+      - set-version
+      - go/load-cache
+      - go/mod-download
+      - go/save-cache
+      - run:
+          name: install-tools
+          command: |
+            go get -u github.com/mitchellh/gox
       - run:
           name: cross compile
           command: |
-            go get .
-            tag=$(semantics --output-tag --dry-run | sed -e "s/^v//")
-            if [ "$tag" ]; then
-              echo "found release version $tag"
-              gox -ldflags "-X github.com/signavio/aws-mfa-login/cmd.Version=$tag" -os="linux darwin windows" -arch="amd64" -output="dist/aws-mfa-login_{{.OS}}_{{.Arch}}"
+            if [ -z "${APP_VERSION}" ]; then
+              export VERSION="${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
             else
-              echo "no new release detected using git SHA1 ${CIRCLE_BRANCH}-${CIRCLE_SHA1} as version"
-              gox -ldflags "-X github.com/signavio/aws-mfa-login/cmd.Version=${CIRCLE_BRANCH}-${CIRCLE_SHA1}" -os="linux darwin windows" -arch="amd64" -output="dist/aws-mfa-login_{{.OS}}_{{.Arch}}"
+              export VERSION="${APP_VERSION}"
             fi
-            ./dist/aws-mfa-login_linux_amd64 --version
+            gox -ldflags "-X 'main.Version=${VERSION}'" -os="linux darwin windows" -arch="amd64" -output="dist/${CIRCLE_PROJECT_REPONAME}_{{.OS}}_{{.Arch}}"
+            ./dist/${CIRCLE_PROJECT_REPONAME}_linux_amd64 version
             cd dist/ && gzip *
       - persist_to_workspace:
+          name: save distributions
           root: .
           paths:
-            - dist/*
+            - ./dist
 
   publish:
-    docker:
-      - image: circleci/golang:1.12
-    working_directory: /go/src/github.com/signavio/aws-mfa-login
+    executor: node/default
     steps:
       - checkout
       - attach_workspace:
           at: .
       - run:
-          name: install-tools
           command: |
-            go get -u github.com/tcnksm/ghr
-            go get -u github.com/stevenmatthewt/semantics
-      - add_ssh_keys:
-          fingerprints:
-            - "f8:92:a9:8a:62:4f:4a:f2:3a:52:aa:b9:7e:05:72:b6"
+            npm install
       - run:
-          name: create release
+          name: release
           command: |
-            tag=$(semantics --output-tag)
-            if [ "$tag" ]; then
-              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $tag dist/
-            else
-              echo "The commit message(s) did not indicate a major/minor/patch version."
-            fi
+            npx semantic-release
 
 workflows:
   build-publish:
     jobs:
-      - build
+      - get-version
+      - build:
+          context: npm-github
+          requires:
+            - get-version
+      - test
       - publish:
           requires:
             - build
+            - test
+          context: npm-github
           filters:
             branches:
               only: master
